/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package to.do_list;

import javax.swing.*;
/**
 *
 * @author Sanele
 */
public class dialogCalendar extends javax.swing.JDialog {

    /**
     * Creates new form dialogCalendar
     */
    public dialogCalendar() {
        super(null, "Calendar", JDialog.ModalityType.APPLICATION_MODAL);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDialogPanel = new javax.swing.JPanel();
        jpWindowPane = new javax.swing.JPanel();
        btnAddTasksForToday = new javax.swing.JButton();
        dcTaskDatePicker = new datechooser.beans.DateChooserPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpDialogPanel.setBackground(new java.awt.Color(0, 204, 204));

        jpWindowPane.setBackground(new java.awt.Color(255, 255, 255));

        btnAddTasksForToday.setBackground(new java.awt.Color(255, 255, 255));
        btnAddTasksForToday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddTasksForToday.setText("Add Tasks For Today");
        btnAddTasksForToday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        btnAddTasksForToday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTasksForTodayActionPerformed(evt);
            }
        });

        dcTaskDatePicker.setCalendarBackground(new java.awt.Color(153, 255, 255));
        dcTaskDatePicker.setNavigateFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 11));

        javax.swing.GroupLayout jpWindowPaneLayout = new javax.swing.GroupLayout(jpWindowPane);
        jpWindowPane.setLayout(jpWindowPaneLayout);
        jpWindowPaneLayout.setHorizontalGroup(
            jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpWindowPaneLayout.createSequentialGroup()
                .addGroup(jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpWindowPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddTasksForToday, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpWindowPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dcTaskDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpWindowPaneLayout.setVerticalGroup(
            jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpWindowPaneLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(dcTaskDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddTasksForToday, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpDialogPanelLayout = new javax.swing.GroupLayout(jpDialogPanel);
        jpDialogPanel.setLayout(jpDialogPanelLayout);
        jpDialogPanelLayout.setHorizontalGroup(
            jpDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpWindowPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpDialogPanelLayout.setVerticalGroup(
            jpDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpWindowPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTasksForTodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTasksForTodayActionPerformed
        dialogTask task = new dialogTask();
    }//GEN-LAST:event_btnAddTasksForTodayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogCalendar dialog = new dialogCalendar();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTasksForToday;
    private datechooser.beans.DateChooserPanel dcTaskDatePicker;
    private javax.swing.JPanel jpDialogPanel;
    private javax.swing.JPanel jpWindowPane;
    // End of variables declaration//GEN-END:variables
}
