/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package to.do_list;

import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Sanele
 */
public class dialogActivities extends JDialog {
    
    private dialogActivities() {
    }
    /**
     * Creates new form dialogActivities
     * @param strDay
     */
    public dialogActivities(String strDay) {
        super(null, strDay +" to-do List", JDialog.ModalityType.APPLICATION_MODAL);
        initComponents();
        lblDialogHeading.setText(strDay+ " Tasks");
        this.strDay = strDay;
        JTextArea[] arrTextArea = new JTextArea[]{
          txtTask1, txtTask2, txtTask3, txtTask4, txtTask5, txtTask6  
        };
        mPrepareTextArea(arrTextArea);
        new frmToDoList().mPrepareLabel(lblDialogHeading);
        new frmToDoList().mPrepareLabel(lblDialogFooter);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    private String strDay;
    
    public String mGetDay(){
        return strDay;
    }
    
    public void mSetValuesToGUI(String strTask0ne, String strTaskTwo, String strTaskThree,
            String strTaskFour, String strTaskFive, String strTaskSix){
        txtTask1.setText(strTask0ne);
        txtTask2.setText(strTaskTwo);
        txtTask3.setText(strTaskThree);
        txtTask4.setText(strTaskFour);
        txtTask5.setText(strTaskFive);
        txtTask6.setText(strTaskSix);
    }
    
    private void mPrepareTextArea(JTextArea[] arrTxtArea) {
        for (JTextArea txtArea : arrTxtArea) {
            txtArea.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    if(e.getClickCount() == 2) {
                        super.mouseClicked(e);
                        dialogTask task = new dialogTask();
                    }
                }
            });
            txtArea.setWrapStyleWord(true);
            txtArea.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDialogPanel = new javax.swing.JPanel();
        jpWindowPane = new javax.swing.JPanel();
        lblDialogHeading = new javax.swing.JLabel();
        lblDialogFooter = new javax.swing.JLabel();
        spTask1ScrollPane = new javax.swing.JScrollPane();
        txtTask1 = new javax.swing.JTextArea();
        spTask2ScrollPane = new javax.swing.JScrollPane();
        txtTask2 = new javax.swing.JTextArea();
        spTask3ScrollPane = new javax.swing.JScrollPane();
        txtTask3 = new javax.swing.JTextArea();
        spTask4ScrollPane = new javax.swing.JScrollPane();
        txtTask4 = new javax.swing.JTextArea();
        spTask5ScrollPane = new javax.swing.JScrollPane();
        txtTask5 = new javax.swing.JTextArea();
        spTask6ScrollPane = new javax.swing.JScrollPane();
        txtTask6 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jpDialogPanel.setBackground(new java.awt.Color(0, 204, 204));

        jpWindowPane.setBackground(new java.awt.Color(255, 255, 255));

        lblDialogHeading.setBackground(new java.awt.Color(204, 204, 255));
        lblDialogHeading.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDialogHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDialogHeading.setText("Day Tasks");

        lblDialogFooter.setBackground(new java.awt.Color(204, 204, 255));
        lblDialogFooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtTask1.setColumns(20);
        txtTask1.setRows(5);
        spTask1ScrollPane.setViewportView(txtTask1);

        txtTask2.setColumns(20);
        txtTask2.setRows(5);
        spTask2ScrollPane.setViewportView(txtTask2);

        txtTask3.setColumns(20);
        txtTask3.setRows(5);
        spTask3ScrollPane.setViewportView(txtTask3);

        txtTask4.setColumns(20);
        txtTask4.setRows(5);
        spTask4ScrollPane.setViewportView(txtTask4);

        txtTask5.setColumns(20);
        txtTask5.setRows(5);
        spTask5ScrollPane.setViewportView(txtTask5);

        txtTask6.setColumns(20);
        txtTask6.setRows(5);
        spTask6ScrollPane.setViewportView(txtTask6);

        javax.swing.GroupLayout jpWindowPaneLayout = new javax.swing.GroupLayout(jpWindowPane);
        jpWindowPane.setLayout(jpWindowPaneLayout);
        jpWindowPaneLayout.setHorizontalGroup(
            jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpWindowPaneLayout.createSequentialGroup()
                .addGroup(jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpWindowPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDialogHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpWindowPaneLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDialogFooter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpWindowPaneLayout.createSequentialGroup()
                                .addGroup(jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpWindowPaneLayout.createSequentialGroup()
                                        .addComponent(spTask4ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                        .addComponent(spTask5ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpWindowPaneLayout.createSequentialGroup()
                                        .addComponent(spTask1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spTask2ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spTask3ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spTask6ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(20, 20, 20))
        );
        jpWindowPaneLayout.setVerticalGroup(
            jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpWindowPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblDialogHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(spTask1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spTask2ScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spTask3ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpWindowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTask4ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spTask5ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spTask6ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(lblDialogFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jpDialogPanelLayout = new javax.swing.GroupLayout(jpDialogPanel);
        jpDialogPanel.setLayout(jpDialogPanelLayout);
        jpDialogPanelLayout.setHorizontalGroup(
            jpDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpWindowPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpDialogPanelLayout.setVerticalGroup(
            jpDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpWindowPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogActivities dialog = new dialogActivities();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpDialogPanel;
    private javax.swing.JPanel jpWindowPane;
    private javax.swing.JLabel lblDialogFooter;
    private javax.swing.JLabel lblDialogHeading;
    private javax.swing.JScrollPane spTask1ScrollPane;
    private javax.swing.JScrollPane spTask2ScrollPane;
    private javax.swing.JScrollPane spTask3ScrollPane;
    private javax.swing.JScrollPane spTask4ScrollPane;
    private javax.swing.JScrollPane spTask5ScrollPane;
    private javax.swing.JScrollPane spTask6ScrollPane;
    private javax.swing.JTextArea txtTask1;
    private javax.swing.JTextArea txtTask2;
    private javax.swing.JTextArea txtTask3;
    private javax.swing.JTextArea txtTask4;
    private javax.swing.JTextArea txtTask5;
    private javax.swing.JTextArea txtTask6;
    // End of variables declaration//GEN-END:variables
}
