/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package to.do_list;

import java.awt.*;
import javax.swing.*;
import to.do_list.assignmentManagaer.*;

/**
 *
 * @author Sanele
 */
public class frmToDoList extends javax.swing.JFrame {

    /**
     * Creates new form frmToDoList
     */
    public frmToDoList() {
        initComponents();
        this.setLocationRelativeTo(null);
        mPrepareLabel(lblfrmMainHeader);
        mPrepareLabel(lblfrmMainFooter);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    public void mPrepareLabel(JLabel lbl) {
        lbl.setOpaque(true);
        lbl.setBackground(new Color(204,204,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMainPanel = new javax.swing.JPanel();
        lblfrmMainHeader = new javax.swing.JLabel();
        lblfrmMainFooter = new javax.swing.JLabel();
        jpCenterPanel = new javax.swing.JPanel();
        btnTuesday = new javax.swing.JButton();
        btnMonday = new javax.swing.JButton();
        btnWednesday = new javax.swing.JButton();
        btnSaturday = new javax.swing.JButton();
        btnSunday = new javax.swing.JButton();
        btnFriday = new javax.swing.JButton();
        btnThursday = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuItemCalendar = new javax.swing.JMenuItem();
        mnuItemExit = new javax.swing.JMenuItem();
        mnuAssignmentManager = new javax.swing.JMenu();
        mnuItemAssignmentManager = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpMainPanel.setBackground(new java.awt.Color(0, 204, 204));

        lblfrmMainHeader.setBackground(new java.awt.Color(204, 204, 255));
        lblfrmMainHeader.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblfrmMainHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfrmMainHeader.setText("Weekly To-do List");

        lblfrmMainFooter.setBackground(new java.awt.Color(204, 204, 255));
        lblfrmMainFooter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblfrmMainFooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jpCenterPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnTuesday.setBackground(new java.awt.Color(255, 255, 255));
        btnTuesday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTuesday.setText("Tuesday");
        btnTuesday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        btnTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuesdayActionPerformed(evt);
            }
        });

        btnMonday.setBackground(new java.awt.Color(255, 255, 255));
        btnMonday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMonday.setText("Monday");
        btnMonday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        btnMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMondayActionPerformed(evt);
            }
        });

        btnWednesday.setBackground(new java.awt.Color(255, 255, 255));
        btnWednesday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnWednesday.setText("Wednesday");
        btnWednesday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        btnWednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWednesdayActionPerformed(evt);
            }
        });

        btnSaturday.setBackground(new java.awt.Color(255, 255, 255));
        btnSaturday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSaturday.setText("Saturday");
        btnSaturday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        btnSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaturdayActionPerformed(evt);
            }
        });

        btnSunday.setBackground(new java.awt.Color(255, 255, 255));
        btnSunday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSunday.setText("Sunday");
        btnSunday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        btnSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSundayActionPerformed(evt);
            }
        });

        btnFriday.setBackground(new java.awt.Color(255, 255, 255));
        btnFriday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFriday.setText("Friday");
        btnFriday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        btnFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFridayActionPerformed(evt);
            }
        });

        btnThursday.setBackground(new java.awt.Color(255, 255, 255));
        btnThursday.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThursday.setText("Thursday");
        btnThursday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        btnThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThursdayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCenterPanelLayout = new javax.swing.GroupLayout(jpCenterPanel);
        jpCenterPanel.setLayout(jpCenterPanelLayout);
        jpCenterPanelLayout.setHorizontalGroup(
            jpCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCenterPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThursday, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSunday, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jpCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCenterPanelLayout.createSequentialGroup()
                        .addComponent(btnFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnSaturday, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCenterPanelLayout.createSequentialGroup()
                        .addComponent(btnTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jpCenterPanelLayout.setVerticalGroup(
            jpCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCenterPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jpCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaturday, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThursday, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnSunday, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jpMainPanelLayout = new javax.swing.GroupLayout(jpMainPanel);
        jpMainPanel.setLayout(jpMainPanelLayout);
        jpMainPanelLayout.setHorizontalGroup(
            jpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpCenterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfrmMainFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfrmMainHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jpMainPanelLayout.setVerticalGroup(
            jpMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblfrmMainHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jpCenterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(lblfrmMainFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        mnuFile.setText("File");

        mnuItemCalendar.setText("Calendar");
        mnuItemCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCalendarActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemCalendar);

        mnuItemExit.setText("Exit");
        mnuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemExit);

        jMenuBar1.add(mnuFile);

        mnuAssignmentManager.setText("Assignment Manager");

        mnuItemAssignmentManager.setText("Manage Assignments");
        mnuItemAssignmentManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAssignmentManagerActionPerformed(evt);
            }
        });
        mnuAssignmentManager.add(mnuItemAssignmentManager);

        jMenuBar1.add(mnuAssignmentManager);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMondayActionPerformed
        dialogActivities mondayActivities = new dialogActivities(btnMonday.getText());
        new ToDo_List(mondayActivities).mSetToGUI();
        mondayActivities.setVisible(true);
    }//GEN-LAST:event_btnMondayActionPerformed

    private void btnTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuesdayActionPerformed
        dialogActivities tuesdayActivities = new dialogActivities(btnTuesday.getText());
        new ToDo_List(tuesdayActivities).mSetToGUI();
        tuesdayActivities.setVisible(true);
    }//GEN-LAST:event_btnTuesdayActionPerformed

    private void btnWednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWednesdayActionPerformed
        dialogActivities wednesdayActivities = new dialogActivities(btnWednesday.getText());
        new ToDo_List(wednesdayActivities).mSetToGUI();
        wednesdayActivities.setVisible(true);
    }//GEN-LAST:event_btnWednesdayActionPerformed

    private void btnThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThursdayActionPerformed
        dialogActivities thursdayActivities = new dialogActivities(btnThursday.getText());
        new ToDo_List(thursdayActivities).mSetToGUI();
        thursdayActivities.setVisible(true);
    }//GEN-LAST:event_btnThursdayActionPerformed

    private void btnFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFridayActionPerformed
        dialogActivities fridayActivities = new dialogActivities(btnFriday.getText());
        new ToDo_List(fridayActivities).mSetToGUI();
        fridayActivities.setVisible(true);
    }//GEN-LAST:event_btnFridayActionPerformed

    private void btnSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaturdayActionPerformed
        dialogActivities saturdayActivities = new dialogActivities(btnSaturday.getText());
        new ToDo_List(saturdayActivities).mSetToGUI();
        saturdayActivities.setVisible(true);
    }//GEN-LAST:event_btnSaturdayActionPerformed

    private void btnSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSundayActionPerformed
        dialogActivities sundayActivities = new dialogActivities(btnSunday.getText());
        new ToDo_List(sundayActivities).mSetToGUI();
        sundayActivities.setVisible(true);
    }//GEN-LAST:event_btnSundayActionPerformed

    private void mnuItemCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCalendarActionPerformed
        dialogCalendar calendar = new dialogCalendar();
        calendar.setVisible(true);
    }//GEN-LAST:event_mnuItemCalendarActionPerformed

    private void mnuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItemExitActionPerformed

    private void mnuItemAssignmentManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAssignmentManagerActionPerformed
        Assignments.main(new String[0]);
    }//GEN-LAST:event_mnuItemAssignmentManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmToDoList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFriday;
    private javax.swing.JButton btnMonday;
    private javax.swing.JButton btnSaturday;
    private javax.swing.JButton btnSunday;
    private javax.swing.JButton btnThursday;
    private javax.swing.JButton btnTuesday;
    private javax.swing.JButton btnWednesday;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jpCenterPanel;
    private javax.swing.JPanel jpMainPanel;
    private javax.swing.JLabel lblfrmMainFooter;
    private javax.swing.JLabel lblfrmMainHeader;
    private javax.swing.JMenu mnuAssignmentManager;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuItemAssignmentManager;
    private javax.swing.JMenuItem mnuItemCalendar;
    private javax.swing.JMenuItem mnuItemExit;
    // End of variables declaration//GEN-END:variables
}
